import { Inter } from "next/font/google";
import "./globals.css";
import config from "@/config/config.json";
import Footer from "@/layouts/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: config.site.title,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}  
        <Footer />
      </body>
    </html>
  );
}
